// School LOR requirements data
// Sources: AMCAS general guidance, school admissions pages, MSAR (medical)
// Always verify current requirements at official school websites

const medicalSchools = [
  {
    name: "Albany Medical College",
    slug: "albany-medical-college",
    state: "New York",
    city: "Albany",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter accepted, not required",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Albany Medical College reviews letters of recommendation as part of its holistic admissions process. Letters help the committee understand an applicant beyond grades and test scores by providing direct observations from faculty, mentors, and supervisors who can speak to academic readiness, professionalism, and interpersonal qualities.",
      requirementsDetail: "Most competitive applicants submit between three and six letters. A typical package includes two letters from science faculty who taught or supervised the applicant in a laboratory or classroom setting, and at least one letter from a non-science recommender such as a physician, service supervisor, research mentor, or academic advisor. Albany accepts committee letters from pre-medical advisory offices but does not require them.",
      whoShouldWrite: "The strongest letters come from people who know the applicant well and can describe specific observations. A science professor who graded papers, supervised lab work, or held regular office hours with the applicant can speak to academic rigor. A physician, volunteer supervisor, or clinical mentor can speak to service motivation, communication, and professionalism. Research mentors are especially valuable for applicants who completed significant research.",
      howToSubmit: "All letters are submitted through the AMCAS Letter Service. Applicants assign letters to individual school applications after letters are uploaded. Letter authors receive a unique link to upload directly. AMCAS does not forward letters with incomplete applications, so all letters should be uploaded before or shortly after the primary application is verified.",
      tips: "Ask recommenders early, ideally three to four months before the application opens. Provide each recommender with your personal statement draft, a copy of your activities list, a transcript, and two or three specific examples of work you completed together. A well-informed recommender writes a more specific and credible letter. Follow up with a thank-you after submission."
    },
    keywords: "albany medical college letters of recommendation, albany medical college lor requirements, albany medical school letter of recommendation requirements, albany medical college recommendation letter",
    description: "Learn the letter of recommendation requirements for Albany Medical College, including how many letters you need, who should write them, and how to submit through AMCAS."
  },
  {
    name: "Harvard Medical School",
    slug: "harvard-medical-school",
    state: "Massachusetts",
    city: "Boston",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Pre-med committee letter strongly preferred; individual letters accepted if no committee available",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Harvard Medical School treats letters of recommendation as a critical part of holistic review. Because HMS receives thousands of applications, letters from people with direct knowledge of the applicant can provide meaningful differentiation by describing intellectual rigor, clinical judgment, resilience, character, and interpersonal effectiveness in concrete terms.",
      requirementsDetail: "HMS strongly prefers a committee letter from a pre-medical advisory committee. If the applicant's undergraduate institution does not have a committee, three or more individual letters are required. A typical package includes two science faculty letters and at least one letter from a supervisor who can speak to non-academic qualities such as service, empathy, or leadership. HMS typically accepts up to six letters through AMCAS.",
      whoShouldWrite: "The most useful letters come from faculty who taught the applicant in upper-level science courses or supervised independent research, and from mentors who observed the applicant in clinical, service, or leadership settings. Letters that describe specific observations, concrete examples, and meaningful comparisons to other applicants carry more weight than letters focused on grades alone.",
      howToSubmit: "Letters are submitted through the AMCAS Letter Service. The Harvard secondary application may include specific instructions about letter types or the committee letter requirement. Review those instructions carefully each cycle because requirements can change.",
      tips: "For applicants applying from institutions with pre-medical committees, begin the committee letter process well before the application cycle opens. Committee letters often require their own interviews, essays, and transcripts. Individual recommenders should be given at least six to eight weeks to write a thoughtful letter."
    },
    keywords: "harvard medical school letters of recommendation, harvard medical school lor requirements, harvard med school recommendation letter requirements",
    description: "Learn Harvard Medical School's letter of recommendation requirements, including the committee letter preference, number of letters needed, and AMCAS submission process."
  },
  {
    name: "Johns Hopkins School of Medicine",
    slug: "johns-hopkins-school-of-medicine",
    state: "Maryland",
    city: "Baltimore",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Johns Hopkins School of Medicine uses letters of recommendation to assess qualities that are difficult to evaluate through grades and test scores alone, including intellectual curiosity, perseverance, communication, ethical judgment, and commitment to medicine. The admissions committee looks for letters that describe the applicant's contributions in academic and clinical settings with specific, credible examples.",
      requirementsDetail: "Johns Hopkins prefers a composite committee letter from the applicant's undergraduate institution. Applicants from schools without pre-medical committees should submit a minimum of three individual letters, typically including two science faculty letters and at least one letter from a physician, clinical supervisor, or research mentor. A maximum of six letters is typically accepted through AMCAS.",
      whoShouldWrite: "The most effective letters for Johns Hopkins come from faculty who taught upper-level courses or supervised independent research, and from clinical or service supervisors who can describe direct observations of patient interaction, professionalism, and motivation. Letters should go beyond academic performance to include character and interpersonal qualities.",
      howToSubmit: "All letters are submitted through the AMCAS Letter Service. Applicants should review the Johns Hopkins secondary application each cycle for updated letter requirements or any program-specific instructions for the MD-PhD, MD-MPH, or other dual-degree tracks.",
      tips: "Start the committee letter process early if your school offers one. Johns Hopkins admissions is highly competitive, and a thoughtfully coordinated letter package can reinforce themes in your personal statement and activities list. Brief each recommender on the qualities you want highlighted and the experiences you shared with them."
    },
    keywords: "johns hopkins school of medicine letters of recommendation, johns hopkins medical school lor, johns hopkins med school recommendation requirements",
    description: "Learn Johns Hopkins School of Medicine's letter of recommendation requirements, including committee letter preferences and how to submit through AMCAS."
  },
  {
    name: "Yale School of Medicine",
    slug: "yale-school-of-medicine",
    state: "Connecticut",
    city: "New Haven",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter strongly preferred",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Yale School of Medicine evaluates letters of recommendation for evidence of intellectual ability, personal integrity, clinical aptitude, and commitment to medicine as a career of service. The committee pays particular attention to letters that can describe the applicant's growth over time and their impact on the people around them.",
      requirementsDetail: "Yale strongly prefers a committee letter from the applicant's pre-medical advisory office. Applicants without committee support should submit at least three individual letters. A typical letter package includes two letters from science faculty and at least one from a non-academic supervisor or mentor. Yale generally accepts up to six letters through AMCAS.",
      whoShouldWrite: "Letters from science faculty who supervised research or taught courses where the applicant demonstrated analytical ability are especially useful. Letters from physicians, service coordinators, or clinical supervisors can speak to empathy, patient communication, and commitment to care. Yale values letters from recommenders who can describe the applicant's character beyond the transcript.",
      howToSubmit: "Letters are submitted through the AMCAS Letter Service. Check the Yale secondary application each cycle for any updates to letter requirements or instructions for specific programs.",
      tips: "Yale's curriculum emphasizes independent inquiry and collaborative learning. If your recommenders can speak to intellectual curiosity, self-directed learning, or research initiative, those themes align well with Yale's academic culture. Provide recommenders with specific examples of your best work together."
    },
    keywords: "yale school of medicine letters of recommendation, yale medical school lor requirements, yale med school recommendation letter",
    description: "Learn Yale School of Medicine's letter of recommendation requirements, including how many letters to submit, who should write them, and the AMCAS submission process."
  },
  {
    name: "Stanford School of Medicine",
    slug: "stanford-school-of-medicine",
    state: "California",
    city: "Stanford",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Stanford School of Medicine uses letters of recommendation to evaluate the kind of impact an applicant makes on others over time. The admissions committee looks for letters that go beyond academic credentials to describe intellectual creativity, clinical empathy, leadership, and purpose in choosing medicine.",
      requirementsDetail: "Stanford prefers a committee letter from the applicant's undergraduate institution. Applicants from schools without committees should submit at least three individual letters, including two science faculty letters and one letter from a clinical, research, or service supervisor. Up to six letters are typically accepted through AMCAS.",
      whoShouldWrite: "Letters from faculty who can speak to the applicant's research contributions or performance in advanced coursework are particularly useful. Stanford also values letters from people who have observed the applicant in service or clinical settings where teamwork, communication, and patient interaction were involved. Letters that reflect personal knowledge carry more weight than brief endorsements.",
      howToSubmit: "All letters are submitted through the AMCAS Letter Service. Applicants should also review the Stanford secondary application for any program-specific instructions, especially for the MD-PhD program.",
      tips: "Stanford's culture emphasizes innovation and collaboration. Recommenders who can speak to the applicant's creative problem-solving, interdisciplinary thinking, or entrepreneurial approach to medicine can provide perspective that complements the personal statement."
    },
    keywords: "stanford school of medicine letters of recommendation, stanford medical school lor requirements, stanford med recommendation letter",
    description: "Learn Stanford School of Medicine's letter of recommendation requirements, including committee letter preferences, number of letters, and AMCAS submission details."
  },
  {
    name: "Duke University School of Medicine",
    slug: "duke-university-school-of-medicine",
    state: "North Carolina",
    city: "Durham",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter strongly preferred; three individual letters required if no committee available",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Duke University School of Medicine uses letters of recommendation as part of a comprehensive review process that evaluates academic excellence, research potential, clinical aptitude, and character. Duke's curriculum includes a research year for all MD students, so letters that speak to scientific curiosity and independent inquiry are particularly valuable.",
      requirementsDetail: "Duke strongly prefers a committee letter. Applicants without access to a committee must submit at least three individual letters, typically including two science faculty letters and one letter from a clinical, research, or community supervisor. Duke accepts up to six letters through AMCAS.",
      whoShouldWrite: "For Duke, letters from research mentors who can speak to the applicant's productivity, intellectual independence, and scientific thinking can be especially persuasive given the research-intensive curriculum. Clinical letters that describe patient communication and empathy round out the package. A letter from a science faculty member who knows the applicant beyond the classroom setting adds credibility.",
      howToSubmit: "Letters are submitted through the AMCAS Letter Service and are assigned to individual school applications by the applicant. Review the Duke secondary application each cycle for updates.",
      tips: "Duke's third-year research year makes research experience particularly relevant. If you have significant research experience, make sure your research mentor can describe your project's scope, your intellectual contributions, and your ability to work independently."
    },
    keywords: "duke medical school letters of recommendation, duke university school of medicine lor, duke medical school recommendation requirements",
    description: "Learn Duke University School of Medicine's letter of recommendation requirements, including committee letter preferences, research-focused letter tips, and AMCAS submission."
  },
  {
    name: "Northwestern Feinberg School of Medicine",
    slug: "northwestern-feinberg-school-of-medicine",
    state: "Illinois",
    city: "Chicago",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Northwestern Feinberg School of Medicine reviews letters of recommendation alongside academic records, MCAT scores, research experience, and essays to build a complete picture of the applicant. Letters are most useful when they describe specific contributions, observable behaviors, and growth that supports the applicant's readiness for medical training.",
      requirementsDetail: "Northwestern prefers a committee letter from applicants whose undergraduate schools offer pre-medical advising committees. Applicants without committee support should submit three or more individual letters, including two science faculty letters and at least one letter from a supervisor in a clinical, service, or research setting. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "The strongest letters for Northwestern come from faculty who supervised meaningful research or taught advanced coursework, and from clinical or service supervisors who can describe the applicant's interpersonal effectiveness, patient communication, and commitment. Letters that describe a consistent pattern of behavior over time are more persuasive than brief endorsements.",
      howToSubmit: "Letters are submitted through AMCAS. Northwestern's secondary application may include specific instructions for the MD-PhD or other combined programs.",
      tips: "Northwestern values diversity of experience and perspective. If your recommenders can speak to leadership, community engagement, or unique personal history in addition to academic and clinical performance, those dimensions strengthen the overall application."
    },
    keywords: "northwestern feinberg letters of recommendation, northwestern medical school lor requirements, northwestern med school recommendation letter",
    description: "Learn Northwestern Feinberg School of Medicine's letter of recommendation requirements, including committee letter preferences and how to build a strong letter package."
  },
  {
    name: "Vanderbilt University School of Medicine",
    slug: "vanderbilt-university-school-of-medicine",
    state: "Tennessee",
    city: "Nashville",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter accepted; individual letters acceptable",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Vanderbilt University School of Medicine uses letters of recommendation to evaluate leadership, intellectual curiosity, and commitment to service alongside academic performance. The admissions committee looks for letters that describe the applicant's contributions in a variety of settings and that speak to readiness for the demands of medical school.",
      requirementsDetail: "Vanderbilt accepts committee letters and individual letters. Most competitive applicants submit three to five letters, including two science faculty letters and at least one letter from a clinical, research, or service supervisor. Up to six letters are typically accepted through AMCAS.",
      whoShouldWrite: "Faculty who have supervised research, mentored independent projects, or taught the applicant in demanding coursework are well positioned to write useful letters. Clinical supervisors, service leaders, or community mentors who can describe the applicant's character and motivation add important perspective.",
      howToSubmit: "All letters are submitted through AMCAS. Check the Vanderbilt secondary application for any updated requirements each admissions cycle.",
      tips: "Vanderbilt's culture emphasizes collaboration and community engagement. Letters from recommenders who can speak to the applicant's work with underserved populations, leadership in student organizations, or commitment to health equity can complement the academic letters well."
    },
    keywords: "vanderbilt medical school letters of recommendation, vanderbilt school of medicine lor, vanderbilt med school recommendation requirements",
    description: "Learn Vanderbilt University School of Medicine's letter of recommendation requirements, including how many to submit, who should write them, and AMCAS submission details."
  },
  {
    name: "University of Michigan Medical School",
    slug: "university-of-michigan-medical-school",
    state: "Michigan",
    city: "Ann Arbor",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted from schools without committees",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "The University of Michigan Medical School evaluates letters of recommendation as one part of a holistic review process. Letters provide context that grades and test scores cannot, including how the applicant approaches difficult problems, handles responsibility, and interacts with patients, colleagues, and communities.",
      requirementsDetail: "Michigan prefers a committee letter. Applicants without committee access should submit at least three individual letters. A typical package includes two science faculty letters and one letter from a clinical or community supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Faculty who supervised the applicant over an extended period in research or advanced coursework are especially valuable. Clinical supervisors, volunteer coordinators, and service leaders who can speak to empathy, professionalism, and patient interaction add perspective the academic letters cannot provide.",
      howToSubmit: "Letters are submitted through AMCAS. Michigan's secondary application may include additional instructions for specific tracks or combined programs.",
      tips: "Michigan values both research and service. If you have both dimensions of experience, ensure your letter package reflects that balance. A research mentor and a clinical or service supervisor together with science faculty can paint a complete picture."
    },
    keywords: "university of michigan medical school letters of recommendation, u of m med school lor requirements, michigan medical school recommendation letter",
    description: "Learn University of Michigan Medical School's letter of recommendation requirements, including committee letter preferences and how to build a complete letter package."
  },
  {
    name: "Georgetown University School of Medicine",
    slug: "georgetown-university-school-of-medicine",
    state: "District of Columbia",
    city: "Washington",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters required if no committee",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Georgetown University School of Medicine, guided by its Jesuit mission, considers letters of recommendation as evidence of character, service orientation, and intellectual formation in addition to academic ability. Letters that reflect on the applicant's values, ethical reasoning, and commitment to others align particularly well with Georgetown's mission.",
      requirementsDetail: "Georgetown prefers a committee letter. Applicants without committee support should submit at least three individual letters including two science faculty letters and one letter from a person who can speak to the applicant's service, community engagement, or clinical experience. Up to six letters are typically accepted through AMCAS.",
      whoShouldWrite: "Given Georgetown's mission emphasis, letters from people who have supervised the applicant in service roles, volunteer work, or community health settings are particularly relevant. Science faculty letters and research mentor letters remain important, but a letter from someone who can speak to the applicant's values and motivation for medicine adds distinctive weight.",
      howToSubmit: "Letters are submitted through AMCAS. Review the Georgetown secondary application each cycle for updated guidance.",
      tips: "Georgetown's mission of cura personalis (care for the whole person) shapes its admissions culture. Letters that describe an applicant's genuine curiosity about others, service leadership, or commitment to underserved communities speak directly to what Georgetown looks for."
    },
    keywords: "georgetown medical school letters of recommendation, georgetown university school of medicine lor, georgetown med school recommendation requirements",
    description: "Learn Georgetown University School of Medicine's letter of recommendation requirements, including service-focused letter guidance and AMCAS submission details."
  },
  {
    name: "Emory University School of Medicine",
    slug: "emory-university-school-of-medicine",
    state: "Georgia",
    city: "Atlanta",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter accepted; individual letters acceptable",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Emory University School of Medicine reviews letters of recommendation alongside the full application file to understand the applicant's academic preparation, clinical exposure, research background, and personal character. Letters from people who know the applicant well across different contexts help the committee form a complete impression.",
      requirementsDetail: "Emory accepts committee letters and individual letters. Most applicants submit three to five letters including two science faculty letters and one or two letters from clinical, research, or community supervisors. Up to six letters are generally accepted through AMCAS.",
      whoShouldWrite: "Science faculty who can speak to intellectual rigor and research potential, combined with clinical or service supervisors who have observed patient interaction and professionalism, form the most effective letter packages for Emory. Letters from people who have worked with the applicant over at least one semester or project cycle are more credible than brief acquaintance letters.",
      howToSubmit: "Letters are submitted through AMCAS. Review Emory's secondary application each cycle for any updated requirements.",
      tips: "Emory has a strong public health and global health focus. If your experience includes work with underserved communities, global health programs, or public health research, ensure at least one recommender can speak to that dimension of your background."
    },
    keywords: "emory medical school letters of recommendation, emory university school of medicine lor, emory med school recommendation requirements",
    description: "Learn Emory University School of Medicine's letter of recommendation requirements, including how many letters to submit and tips for a strong application package."
  },
  {
    name: "University of California San Francisco (UCSF)",
    slug: "ucsf-school-of-medicine",
    state: "California",
    city: "San Francisco",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; three individual letters required if no committee",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "UCSF School of Medicine emphasizes diversity, research, and service in its mission and uses letters of recommendation to understand how applicants have contributed to those dimensions. Letters help the admissions committee see the applicant through the eyes of people who have observed their work, character, and growth directly.",
      requirementsDetail: "UCSF prefers a committee letter. Applicants without a committee should submit at least three individual letters, including two from science faculty and one from a clinical, research, or community supervisor. UCSF accepts up to six letters through AMCAS.",
      whoShouldWrite: "UCSF values research and innovation, so letters from research mentors who can speak to scientific curiosity and independent thinking carry particular weight. Letters from people who have observed the applicant in clinical or community health settings add evidence of service commitment and patient-centered care.",
      howToSubmit: "Letters are submitted through AMCAS. UCSF's secondary application should be reviewed each cycle for any updated instructions.",
      tips: "UCSF has one of the most diverse and research-intensive medical school environments in the country. Letters that reflect the applicant's connection to diverse communities or research ambition can reinforce themes in the personal statement."
    },
    keywords: "ucsf school of medicine letters of recommendation, ucsf medical school lor requirements, ucsf med school recommendation letter",
    description: "Learn UCSF School of Medicine's letter of recommendation requirements, including committee letter preferences, submission process, and tips for a strong package."
  },
  {
    name: "Icahn School of Medicine at Mount Sinai",
    slug: "icahn-school-of-medicine-mount-sinai",
    state: "New York",
    city: "New York",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter accepted; individual letters acceptable",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Icahn School of Medicine at Mount Sinai evaluates letters of recommendation as part of a holistic review process that values research, clinical commitment, and diversity of background. The FlexMed program and other non-traditional pathways at Mount Sinai attract applicants from varied disciplines, and letters should reflect the applicant's strengths within their own context.",
      requirementsDetail: "Mount Sinai accepts committee letters and individual letters. A typical package for MD applicants includes two science faculty letters and one or two letters from clinical, research, or service supervisors. Up to six letters are accepted through AMCAS. FlexMed applicants should review program-specific letter requirements separately.",
      whoShouldWrite: "For the standard MD program, science faculty and research mentors are appropriate letter writers. For applicants in non-traditional pathways, faculty from any discipline who can speak to analytical thinking, intellectual rigor, and problem-solving are valuable. Clinical or service supervisors who can describe patient interaction and motivation round out a strong package.",
      howToSubmit: "Letters are submitted through AMCAS. Mount Sinai's secondary application may include specific guidance for different programs.",
      tips: "Mount Sinai is known for its research output and diverse patient population. Letters that connect the applicant's background to serving diverse urban communities or contributing to scientific discovery align well with the school's culture."
    },
    keywords: "mount sinai medical school letters of recommendation, icahn school of medicine lor, mount sinai med school recommendation requirements",
    description: "Learn Icahn School of Medicine at Mount Sinai's letter of recommendation requirements for the MD program and tips for submitting through AMCAS."
  },
  {
    name: "New York University (NYU Grossman) School of Medicine",
    slug: "nyu-grossman-school-of-medicine",
    state: "New York",
    city: "New York",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter accepted; individual letters acceptable",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "NYU Grossman School of Medicine, which offers full-tuition scholarships to all admitted students, uses letters of recommendation to evaluate the qualities that distinguish exceptional applicants. Because NYU is highly competitive, letters that describe specific achievements and personal observations are more effective than general endorsements.",
      requirementsDetail: "NYU accepts committee letters and individual letters. Most applicants submit three to five letters including two science faculty letters and one or two letters from clinical, research, or community supervisors. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Given NYU's competitive applicant pool, letters that can speak to the applicant's exceptional intellectual ability, clinical instincts, or leadership potential carry more weight. Faculty who have seen the applicant perform at a high level in demanding settings, and clinical supervisors who can describe patient interactions, are the most effective letter writers.",
      howToSubmit: "Letters are submitted through AMCAS. Review NYU's secondary application each cycle for current requirements.",
      tips: "NYU's scholarship program attracts highly competitive applicants. Letters that can describe the applicant's unique contribution to a research team, a clinical environment, or a community add distinction to the file."
    },
    keywords: "nyu grossman school of medicine letters of recommendation, nyu medical school lor requirements, nyu med school recommendation letter",
    description: "Learn NYU Grossman School of Medicine's letter of recommendation requirements, including how to submit through AMCAS and tips for building a competitive letter package."
  },
  {
    name: "Boston University Chobanian and Avedisian School of Medicine",
    slug: "boston-university-school-of-medicine",
    state: "Massachusetts",
    city: "Boston",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Boston University Chobanian and Avedisian School of Medicine evaluates letters of recommendation as evidence of academic achievement, service to community, and personal character. BU's strong community health and primary care mission shapes the qualities it looks for in applicants and in their recommendation letters.",
      requirementsDetail: "BU prefers a committee letter from applicants whose schools offer pre-medical advising committees. Applicants without committee support should submit at least three individual letters including two science faculty letters and one letter from a clinical or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Letters from faculty who supervised research or taught advanced science courses, combined with letters from clinical or community health supervisors, form the most useful packages for BU. Given BU's primary care and community health focus, letters from mentors who observed the applicant working with underserved or diverse populations are particularly relevant.",
      howToSubmit: "Letters are submitted through AMCAS. Review BU's secondary application for any updated guidance.",
      tips: "BU values commitment to community health and social determinants of medicine. Letters that describe the applicant's work in free clinics, community health organizations, or underserved settings add relevant context to the file."
    },
    keywords: "boston university school of medicine letters of recommendation, BU medical school lor requirements, BU med school recommendation letter",
    description: "Learn Boston University School of Medicine's letter of recommendation requirements, including committee letter preferences and community health letter tips."
  },
  {
    name: "University of Pittsburgh School of Medicine",
    slug: "university-of-pittsburgh-school-of-medicine",
    state: "Pennsylvania",
    city: "Pittsburgh",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "University of Pittsburgh School of Medicine uses letters of recommendation as part of a holistic evaluation that also considers research experience, clinical exposure, community service, and personal statement. Pitt has historically emphasized research and innovation, and letters that speak to scientific ability and independent thinking are particularly valued.",
      requirementsDetail: "Pitt prefers a committee letter. Applicants without committee access should submit at least three individual letters including two science faculty letters and one from a research, clinical, or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Given Pitt's research strength, letters from faculty who supervised independent research or laboratory work can be especially effective. Clinical supervisors, community health mentors, and service leaders who have observed the applicant's patient communication and empathy add balance to the package.",
      howToSubmit: "Letters are submitted through AMCAS. Check Pitt's secondary application each cycle for current guidance.",
      tips: "Pitt has a strong research infrastructure and hospital system affiliation with UPMC. If you completed research at Pitt or in affiliated programs, a letter from your supervisor there can be particularly well-received."
    },
    keywords: "university of pittsburgh school of medicine letters of recommendation, pitt med school lor requirements, upmc medical school recommendation letter",
    description: "Learn University of Pittsburgh School of Medicine's letter of recommendation requirements, including research-focused letter tips and AMCAS submission details."
  },
  {
    name: "Case Western Reserve University School of Medicine",
    slug: "case-western-reserve-school-of-medicine",
    state: "Ohio",
    city: "Cleveland",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Case Western Reserve University School of Medicine evaluates letters of recommendation as part of its holistic admissions process. CWRU has a research-intensive curriculum with early clinical exposure, and letters that describe the applicant's scientific ability, clinical empathy, and collaborative spirit align well with the program's culture.",
      requirementsDetail: "Case Western prefers a committee letter. Applicants without committee access should submit at least three individual letters including two science faculty letters and one from a clinical, research, or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Faculty who supervised research or taught the applicant in upper-level science courses are well-positioned to write effective letters. Clinical or service supervisors who can describe patient interaction and communication add important balance. Given CWRU's collaborative culture, letters that describe the applicant's ability to work in teams or mentor others can be particularly effective.",
      howToSubmit: "Letters are submitted through AMCAS. Review Case Western's secondary application for updated requirements.",
      tips: "Case Western's University Program (integrated with undergraduate studies) and its research-heavy curriculum reward applicants who can demonstrate early research and clinical exposure. Letters that describe longitudinal involvement in research or clinical environments, rather than brief shadowing, carry more weight."
    },
    keywords: "case western reserve school of medicine letters of recommendation, case western medical school lor, cwru med school recommendation requirements",
    description: "Learn Case Western Reserve University School of Medicine's letter of recommendation requirements, including research-focused tips and AMCAS submission process."
  },
  {
    name: "Baylor College of Medicine",
    slug: "baylor-college-of-medicine",
    state: "Texas",
    city: "Houston",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; three individual letters required without committee",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Baylor College of Medicine uses letters of recommendation as part of a holistic review that emphasizes academic excellence, research productivity, and service commitment. BCM's Houston Medical Center location creates a unique culture of research and clinical innovation, and letters that reflect those values are particularly relevant.",
      requirementsDetail: "Baylor prefers a committee letter and requires at least three letters if no committee is available. A typical package includes two science faculty letters and one letter from a research or clinical supervisor. Baylor accepts up to six letters through AMCAS.",
      whoShouldWrite: "Research mentors who can speak to the applicant's scientific output and intellectual initiative are especially valuable at BCM. Clinical supervisors who observed patient care, service leaders, and community health mentors also add important perspective. Letters should describe specific observations rather than general praise.",
      howToSubmit: "Letters are submitted through AMCAS. Review BCM's secondary application each cycle for updated guidance.",
      tips: "BCM has a strong research tradition and Texas Medical Center affiliation. Letters from faculty at BCM-affiliated programs or anyone familiar with the Houston medical environment can add useful context."
    },
    keywords: "baylor college of medicine letters of recommendation, baylor med school lor requirements, BCM recommendation letter requirements",
    description: "Learn Baylor College of Medicine's letter of recommendation requirements, including committee letter policies and AMCAS submission guidance."
  },
  {
    name: "University of North Carolina School of Medicine",
    slug: "university-of-north-carolina-school-of-medicine",
    state: "North Carolina",
    city: "Chapel Hill",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "UNC School of Medicine has a strong commitment to primary care, rural health, and serving North Carolina communities. Letters of recommendation help the admissions committee assess whether applicants are prepared for UNC's mission-driven curriculum and willing to serve diverse patient populations across the state.",
      requirementsDetail: "UNC prefers a committee letter. Applicants without committee access should submit at least three individual letters including two science faculty letters and one from a clinical or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Given UNC's primary care and rural health mission, letters from supervisors who have observed the applicant working with underserved communities, rural health programs, or community health organizations are particularly relevant. Faculty letters and research mentor letters provide the academic dimension.",
      howToSubmit: "Letters are submitted through AMCAS. Review UNC's secondary application each cycle for any updates, particularly regarding in-state applicant requirements.",
      tips: "UNC strongly prioritizes North Carolina residents and applicants with ties to the state's health needs. Letters that connect the applicant's background to serving North Carolina's diverse communities add meaningful context."
    },
    keywords: "unc school of medicine letters of recommendation, unc medical school lor requirements, north carolina medical school recommendation letter",
    description: "Learn University of North Carolina School of Medicine's letter of recommendation requirements, including primary care focus and AMCAS submission details."
  },
  {
    name: "Dartmouth Geisel School of Medicine",
    slug: "dartmouth-geisel-school-of-medicine",
    state: "New Hampshire",
    city: "Hanover",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Dartmouth Geisel School of Medicine emphasizes collaborative, community-focused medical education. The admissions committee uses letters of recommendation to understand how applicants engage with others, approach intellectual challenges, and demonstrate commitment to service over time.",
      requirementsDetail: "Geisel prefers a committee letter. Applicants without committee access should submit at least three individual letters including two science faculty letters and one from a clinical or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Given Geisel's community and collaboration emphasis, letters from people who can speak to the applicant's ability to work in teams, mentor peers, or contribute to group settings are particularly valuable. Faculty letters provide academic credibility, while service and clinical letters demonstrate patient-centered values.",
      howToSubmit: "Letters are submitted through AMCAS. Review Geisel's secondary application each cycle for updates.",
      tips: "Geisel's location in rural New Hampshire and its community health programs attract applicants with rural health or primary care interests. If you have experience in rural health, community health centers, or similar settings, a letter from a supervisor in those contexts can be effective."
    },
    keywords: "dartmouth geisel school of medicine letters of recommendation, dartmouth medical school lor requirements, geisel med school recommendation letter",
    description: "Learn Dartmouth Geisel School of Medicine's letter of recommendation requirements, including community-focused letter tips and AMCAS submission guidance."
  },
  {
    name: "Indiana University School of Medicine",
    slug: "indiana-university-school-of-medicine",
    state: "Indiana",
    city: "Indianapolis",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Indiana University School of Medicine is one of the largest medical schools in the United States and has a strong primary care, rural health, and community medicine mission. Letters of recommendation help the committee understand applicants' academic readiness, service commitment, and suitability for a mission-driven curriculum.",
      requirementsDetail: "IU School of Medicine accepts committee letters and individual letters. A typical package includes two science faculty letters and one or two letters from clinical, service, or research supervisors. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Given IU's primary care mission, letters from clinical supervisors who observed patient care in community settings, rural health programs, or underserved environments are particularly relevant. Science faculty and research mentors provide the academic perspective.",
      howToSubmit: "Letters are submitted through AMCAS. IU has multiple campuses across Indiana, so review the secondary application for campus-specific guidance.",
      tips: "IU strongly values applicants with Indiana roots or demonstrated interest in serving Indiana communities. Letters that speak to the applicant's connection to the state or commitment to primary care add meaningful context."
    },
    keywords: "indiana university school of medicine letters of recommendation, IU school of medicine lor, indiana medical school recommendation requirements",
    description: "Learn Indiana University School of Medicine's letter of recommendation requirements, including primary care focus and multi-campus considerations."
  },
  {
    name: "Ohio State University College of Medicine",
    slug: "ohio-state-university-college-of-medicine",
    state: "Ohio",
    city: "Columbus",
    amcas: true,
    minLetters: 3,
    maxLetters: 6,
    committeeNote: "Committee letter preferred; individual letters accepted",
    scienceLetters: 2,
    nonScienceLetters: 1,
    submissionNote: "Submit through AMCAS Letter Service",
    content: {
      intro: "Ohio State University College of Medicine combines a large research enterprise with a commitment to primary care and community health. Letters of recommendation help the admissions committee evaluate the qualities necessary for success in OSU's clinically integrated curriculum and research environment.",
      requirementsDetail: "Ohio State accepts committee letters and individual letters. Most competitive applicants submit three to five letters including two science faculty letters and at least one from a clinical or service supervisor. Up to six letters are accepted through AMCAS.",
      whoShouldWrite: "Faculty who supervised research at OSU or affiliated programs are positioned to write effective letters. Clinical supervisors, community health mentors, and service leaders who observed patient-focused work add the service dimension. Letters should describe direct observations of performance, not just general character.",
      howToSubmit: "Letters are submitted through AMCAS. Review OSU's secondary application each cycle for updated requirements.",
      tips: "OSU's Wexner Medical Center is a major academic medical system. Letters from supervisors who observed the applicant in Wexner clinical environments, research labs, or affiliated programs add relevant context."
    },
    keywords: "ohio state university college of medicine letters of recommendation, OSU medical school lor requirements, ohio state med school recommendation letter",
    description: "Learn Ohio State University College of Medicine's letter of recommendation requirements, including how to submit through AMCAS and what recommenders to choose."
  }
];

const undergradSchools = [
  {
    name: "Massachusetts Institute of Technology",
    displayName: "MIT",
    slug: "mit",
    state: "Massachusetts",
    city: "Cambridge",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: false,
    platform: "MIT Application",
    notes: "MIT requires two teacher recommendations, at least one from a STEM teacher. A school counselor evaluation is also required. One optional letter from another person who knows the applicant well is accepted.",
    keywords: "does mit require letters of recommendation, mit letters of recommendation requirements, mit recommendation letter undergraduate",
    description: "Find out if MIT requires letters of recommendation for undergraduate admission, how many are needed, and who should write them."
  },
  {
    name: "New York University",
    displayName: "NYU",
    slug: "nyu",
    state: "New York",
    city: "New York",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "NYU requires one counselor recommendation and one teacher recommendation through the Common Application. One additional optional recommendation is accepted. Some NYU programs may have specific requirements.",
    keywords: "does nyu require letters of recommendation, nyu letters of recommendation requirements, nyu recommendation letter undergraduate",
    description: "Find out if NYU requires letters of recommendation, how many are needed, and who submits them through the Common Application."
  },
  {
    name: "Cornell University",
    displayName: "Cornell",
    slug: "cornell",
    state: "New York",
    city: "Ithaca",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Cornell requires a school counselor recommendation and two teacher recommendations through Common App. One optional additional recommendation is accepted. Requirements may vary slightly by college within Cornell.",
    keywords: "does cornell require letters of recommendation, cornell letters of recommendation requirements, cornell recommendation letter undergraduate",
    description: "Find out if Cornell requires letters of recommendation, how many teachers must write, and how to submit through the Common Application."
  },
  {
    name: "Stanford University",
    displayName: "Stanford",
    slug: "stanford",
    state: "California",
    city: "Stanford",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App / Coalition",
    notes: "Stanford requires two teacher letters and one counselor recommendation. Stanford also asks counselors to complete the School Report. One optional additional recommendation is accepted but must add new information not already in the application.",
    keywords: "does stanford require letters of recommendation, stanford letters of recommendation requirements, stanford recommendation letter undergraduate",
    description: "Find out if Stanford requires letters of recommendation, what types are needed, and what makes an effective Stanford letter."
  },
  {
    name: "Yale University",
    displayName: "Yale",
    slug: "yale",
    state: "Connecticut",
    city: "New Haven",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App / QuestBridge",
    notes: "Yale requires two teacher recommendations and one school counselor recommendation. One optional additional recommendation from another teacher, supervisor, or mentor is accepted. Yale reviewers read letters carefully as part of holistic review.",
    keywords: "does yale require letters of recommendation, yale letters of recommendation requirements, yale recommendation letter undergraduate",
    description: "Find out if Yale requires letters of recommendation, how many teachers should write, and what Yale's admissions office looks for in recommendation letters."
  },
  {
    name: "University of California, Los Angeles",
    displayName: "UCLA",
    slug: "ucla",
    state: "California",
    city: "Los Angeles",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "UC Application",
    notes: "UCLA does not require or accept letters of recommendation for most undergraduate applicants. The UC Application uses Personal Insight Questions instead. Some special programs and departments may have different requirements.",
    keywords: "does ucla require letters of recommendation, ucla letters of recommendation undergraduate, ucla recommendation letter policy",
    description: "Find out if UCLA requires letters of recommendation for undergraduate admission — and what you submit instead through the UC Application."
  },
  {
    name: "University of California, Berkeley",
    displayName: "UC Berkeley",
    slug: "uc-berkeley",
    state: "California",
    city: "Berkeley",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "UC Application",
    notes: "UC Berkeley does not require or accept letters of recommendation for most freshmen applicants through the standard UC Application. Applicants submit Personal Insight Questions instead. Certain special programs may have different requirements.",
    keywords: "does uc berkeley require letters of recommendation, uc berkeley letters of recommendation undergraduate, berkeley recommendation letter policy",
    description: "Find out if UC Berkeley requires letters of recommendation and what freshmen submit instead through the UC Application."
  },
  {
    name: "University of Michigan",
    displayName: "University of Michigan",
    slug: "university-of-michigan",
    state: "Michigan",
    city: "Ann Arbor",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "University of Michigan requires one teacher recommendation and one counselor recommendation through Common App. One additional optional recommendation is accepted. Michigan LSA and Engineering may have slightly different expectations.",
    keywords: "does university of michigan require letters of recommendation, u of m letters of recommendation requirements, michigan recommendation letter undergraduate",
    description: "Find out if University of Michigan requires letters of recommendation for undergraduate admission and how to submit through the Common Application."
  },
  {
    name: "University of Wisconsin-Madison",
    displayName: "UW-Madison",
    slug: "uw-madison",
    state: "Wisconsin",
    city: "Madison",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "UW-Madison does not require letters of recommendation for standard freshman undergraduate admission. The application focuses on grades, test scores, essays, and activities. Check specific program requirements as some majors or honors tracks may differ.",
    keywords: "does uw-madison require letters of recommendation, does university of wisconsin require letters of recommendation, uw madison recommendation letter policy",
    description: "Find out if the University of Wisconsin-Madison requires letters of recommendation for undergraduate admission and what the application does require."
  },
  {
    name: "Purdue University",
    displayName: "Purdue",
    slug: "purdue",
    state: "Indiana",
    city: "West Lafayette",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App / Purdue Application",
    notes: "Purdue does not require letters of recommendation for standard freshman admission to most programs. Some programs such as Honors College or certain special admission tracks may ask for one optional recommendation. Always verify with Purdue's admissions office.",
    keywords: "does purdue require letters of recommendation, purdue letters of recommendation undergraduate, purdue recommendation letter policy",
    description: "Find out if Purdue University requires letters of recommendation for undergraduate admission and which programs may have different expectations."
  },
  {
    name: "University of Texas at Austin",
    displayName: "UT Austin",
    slug: "ut-austin",
    state: "Texas",
    city: "Austin",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "ApplyTexas",
    notes: "UT Austin does not require letters of recommendation for standard freshman admission through ApplyTexas. Some programs and honors tracks may have different requirements. Check individual program pages for any additional materials.",
    keywords: "does ut austin require letters of recommendation, ut austin letters of recommendation undergraduate, university of texas recommendation letter policy",
    description: "Find out if UT Austin requires letters of recommendation for undergraduate admission and what the ApplyTexas application does require."
  },
  {
    name: "University of Southern California",
    displayName: "USC",
    slug: "usc",
    state: "California",
    city: "Los Angeles",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 2,
    commonApp: true,
    platform: "Common App",
    notes: "USC requires one counselor recommendation and one teacher recommendation through Common App. Up to two additional optional recommendations are accepted. USC's admissions process is holistic, and letters should add information not already visible in the rest of the application.",
    keywords: "does usc require letters of recommendation, usc letters of recommendation requirements, usc recommendation letter undergraduate",
    description: "Find out if USC requires letters of recommendation for undergraduate admission and how many are needed through the Common Application."
  },
  {
    name: "Georgia Institute of Technology",
    displayName: "Georgia Tech",
    slug: "georgia-tech",
    state: "Georgia",
    city: "Atlanta",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Georgia Tech requires one teacher recommendation and a counselor recommendation through Common App. One optional additional recommendation is accepted. Georgia Tech's STEM focus means teacher recommendations from math or science teachers are often most relevant.",
    keywords: "does georgia tech require letters of recommendation, georgia tech letters of recommendation requirements, georgia tech recommendation letter undergraduate",
    description: "Find out if Georgia Tech requires letters of recommendation, how many are needed, and what types of recommenders are most effective."
  },
  {
    name: "Arizona State University",
    displayName: "ASU",
    slug: "asu",
    state: "Arizona",
    city: "Tempe",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "ASU Application",
    notes: "Arizona State University does not require letters of recommendation for standard freshman admission. The application focuses on grades, course rigor, and test scores. Some honors programs and scholarship applications may have separate requirements.",
    keywords: "does asu require letters of recommendation, arizona state university letters of recommendation, asu recommendation letter policy",
    description: "Find out if Arizona State University requires letters of recommendation for undergraduate admission and what ASU's application does require."
  },
  {
    name: "Clemson University",
    displayName: "Clemson",
    slug: "clemson",
    state: "South Carolina",
    city: "Clemson",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "Clemson does not require letters of recommendation for standard freshman admission. The application focuses on grades, class rank, test scores, and essays. Honors programs may have separate requirements.",
    keywords: "does clemson require letters of recommendation, clemson letters of recommendation undergraduate, clemson recommendation letter policy",
    description: "Find out if Clemson University requires letters of recommendation for undergraduate admission and what the application does require."
  },
  {
    name: "Penn State University",
    displayName: "Penn State",
    slug: "penn-state",
    state: "Pennsylvania",
    city: "University Park",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Penn State does not require letters of recommendation for standard freshman admission but accepts one optional letter. Applicants may submit a recommendation from a teacher, counselor, or employer if they feel it adds meaningful information.",
    keywords: "does penn state require letters of recommendation, penn state letters of recommendation undergraduate, penn state recommendation letter policy",
    description: "Find out if Penn State requires letters of recommendation for undergraduate admission and whether the optional letter is worth submitting."
  },
  {
    name: "University of Central Florida",
    displayName: "UCF",
    slug: "ucf",
    state: "Florida",
    city: "Orlando",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "Common App / UCF Application",
    notes: "UCF does not require letters of recommendation for standard freshman admission. The application focuses on grades, test scores, and short essays. Scholarship and honors programs may have separate letter requirements.",
    keywords: "does ucf require letters of recommendation, ucf letters of recommendation undergraduate, university of central florida recommendation letter policy",
    description: "Find out if UCF requires letters of recommendation for undergraduate admission and what UCF's application does require."
  },
  {
    name: "Florida State University",
    displayName: "FSU",
    slug: "fsu",
    state: "Florida",
    city: "Tallahassee",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "Common App / FSU Application",
    notes: "Florida State University does not require letters of recommendation for standard freshman admission. The application emphasizes grades, test scores, essays, and activities. Scholarship applications may require separate letters.",
    keywords: "does fsu require letters of recommendation, florida state university letters of recommendation, fsu recommendation letter policy",
    description: "Find out if Florida State University requires letters of recommendation for undergraduate admission and what FSU's application does include."
  },
  {
    name: "University of Florida",
    displayName: "UF",
    slug: "uf",
    state: "Florida",
    city: "Gainesville",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "Common App",
    notes: "University of Florida does not require letters of recommendation for standard freshman admission through Common App. The application focuses on grades, test scores, essays, and activities. Specific programs and scholarship tracks may have different requirements.",
    keywords: "does uf require letters of recommendation, university of florida letters of recommendation, uf recommendation letter policy",
    description: "Find out if University of Florida requires letters of recommendation for undergraduate admission and what UF's Common App process does require."
  },
  {
    name: "University of South Florida",
    displayName: "USF",
    slug: "usf",
    state: "Florida",
    city: "Tampa",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "Common App",
    notes: "USF does not require letters of recommendation for standard freshman admission. The application focuses on grades, test scores, and essays. Honors programs and scholarship applications may have separate requirements.",
    keywords: "does usf require letters of recommendation, university of south florida letters of recommendation, usf recommendation letter policy",
    description: "Find out if University of South Florida requires letters of recommendation for undergraduate admission and what USF's application does require."
  },
  {
    name: "San Diego State University",
    displayName: "SDSU",
    slug: "sdsu",
    state: "California",
    city: "San Diego",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "Cal State Apply",
    notes: "SDSU does not require letters of recommendation for standard freshman admission through Cal State Apply. The application focuses on grades and courses. Some competitive programs may have separate requirements.",
    keywords: "does sdsu require letters of recommendation, san diego state university letters of recommendation, sdsu recommendation letter policy",
    description: "Find out if SDSU requires letters of recommendation for undergraduate admission and what the Cal State application requires."
  },
  {
    name: "Duke University",
    displayName: "Duke",
    slug: "duke",
    state: "North Carolina",
    city: "Durham",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App / QuestBridge",
    notes: "Duke requires two teacher recommendations and a counselor recommendation through Common App. One additional optional recommendation is accepted. Duke specifically states that additional materials beyond what is required add value only if they present new and meaningful information.",
    keywords: "does duke require letters of recommendation, duke letters of recommendation requirements, duke university recommendation letter undergraduate",
    description: "Find out if Duke University requires letters of recommendation, how many are needed, and what Duke's admissions process looks for in teacher evaluations."
  },
  {
    name: "Vanderbilt University",
    displayName: "Vanderbilt",
    slug: "vanderbilt",
    state: "Tennessee",
    city: "Nashville",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Vanderbilt requires two teacher recommendations and a counselor recommendation through Common App. One optional additional recommendation is accepted. Vanderbilt's admissions is holistic, and letters should help the reader understand the student as a person, not just a scholar.",
    keywords: "does vanderbilt require letters of recommendation, vanderbilt letters of recommendation requirements, vanderbilt recommendation letter undergraduate",
    description: "Find out if Vanderbilt requires letters of recommendation for undergraduate admission and how many teacher evaluations are needed."
  },
  {
    name: "Georgetown University",
    displayName: "Georgetown",
    slug: "georgetown",
    state: "District of Columbia",
    city: "Washington",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Georgetown requires two teacher recommendations and a school counselor recommendation through Common App. One optional additional recommendation is accepted. Georgetown reads letters carefully as part of its values-driven holistic review process.",
    keywords: "does georgetown require letters of recommendation, georgetown university letters of recommendation requirements, georgetown recommendation letter undergraduate",
    description: "Find out if Georgetown requires letters of recommendation for undergraduate admission and what Georgetown's Jesuit-mission admissions process looks for."
  },
  {
    name: "University of Virginia",
    displayName: "UVA",
    slug: "uva",
    state: "Virginia",
    city: "Charlottesville",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "UVA requires two teacher recommendations and a school counselor recommendation through Common App. One optional additional recommendation is accepted. UVA's admissions committee values letters that describe intellectual engagement and personal character.",
    keywords: "does uva require letters of recommendation, university of virginia letters of recommendation requirements, uva recommendation letter undergraduate",
    description: "Find out if UVA requires letters of recommendation for undergraduate admission and how many teacher evaluations the Common Application needs."
  },
  {
    name: "University of North Carolina at Chapel Hill",
    displayName: "UNC Chapel Hill",
    slug: "unc-chapel-hill",
    state: "North Carolina",
    city: "Chapel Hill",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "UNC Chapel Hill requires one teacher recommendation and a school counselor recommendation through Common App. One optional additional recommendation is accepted. UNC's holistic review looks at the full application, and letters should add meaningful context about the applicant.",
    keywords: "does unc require letters of recommendation, unc chapel hill letters of recommendation requirements, unc recommendation letter undergraduate",
    description: "Find out if UNC Chapel Hill requires letters of recommendation for undergraduate admission and what the Common Application process requires."
  },
  {
    name: "Northeastern University",
    displayName: "Northeastern",
    slug: "northeastern",
    state: "Massachusetts",
    city: "Boston",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Northeastern requires two teacher recommendations and a school counselor recommendation through Common App. One optional additional recommendation is accepted. Given Northeastern's co-op emphasis, letters from employers or co-op supervisors can be especially relevant as optional additions.",
    keywords: "does northeastern require letters of recommendation, northeastern university letters of recommendation requirements, northeastern recommendation letter undergraduate",
    description: "Find out if Northeastern University requires letters of recommendation and whether an employer or co-op letter can strengthen the application."
  },
  {
    name: "Boston University",
    displayName: "BU",
    slug: "boston-university",
    state: "Massachusetts",
    city: "Boston",
    requiresLOR: true,
    requiredCount: 1,
    counselorRequired: true,
    teacherRequired: 1,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Boston University requires one teacher recommendation and a counselor recommendation through Common App. One optional additional recommendation is accepted. BU's holistic review values letters that provide context about the student's intellectual engagement and character.",
    keywords: "does bu require letters of recommendation, boston university letters of recommendation requirements, bu recommendation letter undergraduate",
    description: "Find out if Boston University requires letters of recommendation for undergraduate admission and how to submit through the Common Application."
  },
  {
    name: "University of Washington",
    displayName: "UW",
    slug: "university-of-washington",
    state: "Washington",
    city: "Seattle",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "The University of Washington does not require letters of recommendation for most freshman applicants. The application focuses on grades, test scores, and personal essays. Specific programs or direct-to-major pathways may have different requirements.",
    keywords: "does university of washington require letters of recommendation, uw seattle letters of recommendation undergraduate, university of washington recommendation letter policy",
    description: "Find out if University of Washington requires letters of recommendation for undergraduate admission and what its application does emphasize."
  },
  {
    name: "Ohio State University",
    displayName: "Ohio State",
    slug: "ohio-state",
    state: "Ohio",
    city: "Columbus",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "Ohio State does not require letters of recommendation for standard freshman admission. The application focuses on grades, test scores, and essays. Honors and scholarship programs may have separate requirements.",
    keywords: "does ohio state require letters of recommendation, ohio state university letters of recommendation undergraduate, osu recommendation letter policy",
    description: "Find out if Ohio State University requires letters of recommendation for undergraduate admission and what Ohio State's application does require."
  },
  {
    name: "Carnegie Mellon University",
    displayName: "Carnegie Mellon",
    slug: "carnegie-mellon",
    state: "Pennsylvania",
    city: "Pittsburgh",
    requiresLOR: true,
    requiredCount: 2,
    counselorRequired: true,
    teacherRequired: 2,
    optionalAdditional: 1,
    commonApp: true,
    platform: "Common App",
    notes: "Carnegie Mellon requires two teacher recommendations and a school counselor recommendation through Common App. One optional additional recommendation is accepted. CMU's college-specific programs may have additional guidance, so review the requirements for your specific school within CMU.",
    keywords: "does carnegie mellon require letters of recommendation, cmu letters of recommendation requirements, carnegie mellon recommendation letter undergraduate",
    description: "Find out if Carnegie Mellon requires letters of recommendation for undergraduate admission and what CMU's college-specific requirements look like."
  },
  {
    name: "University of Minnesota Twin Cities",
    displayName: "University of Minnesota",
    slug: "university-of-minnesota",
    state: "Minnesota",
    city: "Minneapolis",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "The University of Minnesota Twin Cities does not require letters of recommendation for standard freshman admission. The application focuses on grades, test scores, and essays. Specific programs, honors college, or scholarship applications may have different requirements.",
    keywords: "does university of minnesota require letters of recommendation, umn letters of recommendation undergraduate, minnesota recommendation letter policy",
    description: "Find out if University of Minnesota requires letters of recommendation for undergraduate admission and what the application does require."
  },
  {
    name: "Texas A&M University",
    displayName: "Texas A&M",
    slug: "texas-am",
    state: "Texas",
    city: "College Station",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: false,
    platform: "ApplyTexas",
    notes: "Texas A&M does not require letters of recommendation for standard freshman admission through ApplyTexas. The application focuses on grades, test scores, and essays. Some competitive programs and engineering tracks may have different requirements.",
    keywords: "does texas a&m require letters of recommendation, texas am letters of recommendation undergraduate, tamu recommendation letter policy",
    description: "Find out if Texas A&M requires letters of recommendation for undergraduate admission and what ApplyTexas does require."
  },
  {
    name: "Virginia Tech",
    displayName: "Virginia Tech",
    slug: "virginia-tech",
    state: "Virginia",
    city: "Blacksburg",
    requiresLOR: false,
    requiredCount: 0,
    counselorRequired: false,
    teacherRequired: 0,
    optionalAdditional: 0,
    commonApp: true,
    platform: "Common App",
    notes: "Virginia Tech does not require letters of recommendation for standard freshman admission. The application focuses on grades, test scores, and short essays. Some programs may have specific requirements.",
    keywords: "does virginia tech require letters of recommendation, vt letters of recommendation undergraduate, virginia tech recommendation letter policy",
    description: "Find out if Virginia Tech requires letters of recommendation for undergraduate admission and what Virginia Tech's application does require."
  }
];

module.exports = { medicalSchools, undergradSchools };
